name: Build and Release

on:
  push:
    branches:
      - master  # master 브랜치에 푸시할 때 트리거

jobs:
  build_csharp:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'  # 사용하는 .NET Core 버전

      - name: Restore dependencies
        run: dotnet restore

      - name: Build C# Project
        run: dotnet build --configuration Release --no-restore

      - name: Test C# Project
        run: dotnet test --no-build --verbosity normal

      - name: Upload C# Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: csharp-build
          path: |
            BlueTelephone\bin\Release\net8.0-windows\

  build_go:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # 사용하는 Go 버전

      - name: Build Go Program
        run: |
          cd background  # Go 프로그램이 있는 디렉토리로 이동
          go build -o blue-telephone-d.exe  # Go 프로그램 빌드

      - name: Upload Go Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-build
          path: background\blue-telephone-d.exe
  
  Archive:
    runs-on: windows-latest
    needs: [build_csharp, build_go]  # C#과 Go 빌드가 모두 완료된 후에 실행

    steps:
      - name: Download C# Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: csharp-build

      - name: Download Go Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: go-build

      - name: Prepare Release Folder
        run: |
          mkdir publish
          copy BlueTelephone\bin\Release\net8.0-windows\* publish\
          copy background\blue-telephone-d.exe publish\blue-telephone-d.exe

      - name: Zip Release Files
        run: |
          powershell Compress-Archive -Path publish\* -DestinationPath release.zip
      
      - name: Extract Version from Commit Message
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE '^v[0-9]+\.[0-9]+\.[0-9]+')
          echo $VERSION > version.txt

      - name: Upload Release Archive
        uses: actions/upload-artifact@v3
        with:
          name: release-archive
          path: release.zip
          retention-days: 1

      - name: Upload Version File
        uses: actions/upload-artifact@v3
        with:
          name: version-file
          path: version.txt
          retention-days: 1

  release:
    needs: Archive 
    runs-on: windows-latest

    steps:
      - name: Download Release Archive
        uses: actions/download-artifact@v3
        with:
          name: release-archive

      - name: Download Version File
        uses: actions/download-artifact@v3
        with:
          name: version-file

      - name: Read Version
        id: read_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Combined Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: BlueTelephone-${{ env.VERSION }}.zip
          asset_content_type: application/zip
